#!/usr/bin/env python3
from pathlib import Path
import base64

# tiny valid jpg bytes (placeholder)
JPG_BASE64 = '/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQEA8QEA8PDw8PDw8PDw8PDw8PFREWFhURFRUYHSggGBolGxUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OGhAQGi0fHyUtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAAEAAQMBIgACEQEDEQH/xAAXAAEBAQEAAAAAAAAAAAAAAAAAAQID/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAEQ/9oADAMBAAIQAxAAAAGwqk//xAAZEAEAAwEBAAAAAAAAAAAAAAABAAIREiH/2gAIAQEAAT8A6K5u3d//xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAgBAgEBPwCf/8QAFhEBAQEAAAAAAAAAAAAAAAAAABEh/9oACAEDAQE/AYf/2Q=='

out = Path('scripts/generated_sample.jpg')
out.write_bytes(base64.b64decode(JPG_BASE64))
print(f'Wrote {out}')
